// Windows 용 `sudal` CLI shim 만들기. macOS 의 ~/.local/bin/sudal(#!/bin/sh)에 해당한다.
// 한 폴더에 sudal.cmd(cmd·PowerShell)와 확장자 없는 sudal(Git Bash — Claude Code 의 Bash 도구가 쓴다)을 함께 둔다.
// npm 이 전역 명령을 까는 방식과 같아서, 그 폴더가 PATH 에 있으면 어느 셸에서든 `sudal` 로 부를 수 있다.

import path from "node:path";

const w = path.win32;

/** %LOCALAPPDATA%\Sudal\bin — 사용자가 설치하는 shim 자리. */
export function windowsCliBinDir(env: NodeJS.ProcessEnv, home: string): string {
  return w.join(env.LOCALAPPDATA || w.join(home, "AppData", "Local"), "Sudal", "bin");
}

/**
 * .cmd 에 넣을 경로 표기. cmd.exe 는 배치 파일을 시스템 코드 페이지(한국어 Windows 는 949)로 읽어서
 * UTF-8 로 쓴 한글 경로(사용자 이름 등)가 깨진다. 그래서 알려진 앞부분을 %LOCALAPPDATA% 같은 변수로 바꿔 ASCII 로 남기고,
 * 나머지의 % 는 %% 로 막는다.
 */
export function cmdPathLiteral(p: string, env: NodeJS.ProcessEnv): string {
  for (const name of ["LOCALAPPDATA", "APPDATA", "USERPROFILE"]) {
    const base = env[name]?.replace(/[\\/]+$/, "");
    if (base && p.toLowerCase().startsWith(`${base.toLowerCase()}\\`)) return `%${name}%${p.slice(base.length).replace(/%/g, "%%")}`;
  }
  return p.replace(/%/g, "%%");
}

export interface ShimTarget {
  /** Sudal.exe(process.execPath) */
  exe: string;
  /** 동봉 resources\cli\sudal.cjs */
  cjs: string;
  /** 이 앱의 userData — SUDAL_USERDATA 기본값 */
  userData: string;
}

/** sudal.cmd. setlocal 로 감싸 ELECTRON_RUN_AS_NODE 가 부른 cmd 세션에 남지 않게 한다. */
export function windowsCmdShim(t: ShimTarget, env: NodeJS.ProcessEnv): string {
  return [
    "@echo off",
    "rem Sudal CLI (generated by the Sudal app; reinstall from Settings to update)",
    "setlocal",
    `if not defined SUDAL_USERDATA set "SUDAL_USERDATA=${cmdPathLiteral(t.userData, env)}"`,
    "set ELECTRON_RUN_AS_NODE=1",
    `"${cmdPathLiteral(t.exe, env)}" "${cmdPathLiteral(t.cjs, env)}" %*`,
    "",
  ].join("\r\n");
}

const shQuote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;

/** Git Bash(MSYS)용 sh 스크립트. 실행 경로는 / 로 바꾼다(MSYS 와 node 모두 C:/... 를 받는다). */
export function windowsShShim(t: ShimTarget): string {
  const fwd = (p: string) => p.replace(/\\/g, "/");
  return [
    "#!/bin/sh",
    "# Sudal CLI (generated by the Sudal app; reinstall from Settings to update)",
    // 기본값은 큰따옴표 안이라 \ " $ ` 만 막으면 원래 표기(C:\...)가 그대로 들어간다 — 앱이 넘기는 값과 같아야 제어 파이프 이름이 맞는다
    `: "\${SUDAL_USERDATA:=${t.userData.replace(/[\\"$`]/g, "\\$&")}}"`,
    "export SUDAL_USERDATA",
    `ELECTRON_RUN_AS_NODE=1 exec ${shQuote(fwd(t.exe))} ${shQuote(fwd(t.cjs))} "$@"`,
    "",
  ].join("\n");
}

/** PATH 값에 dir 이 있는가. win32 는 ; 로 나누고 대소문자·끝 구분자를 무시한다. */
export function pathListHas(pathValue: string, dir: string, platform: NodeJS.Platform): boolean {
  if (platform !== "win32") return pathValue.split(":").some((p) => p.replace(/\/+$/, "") === dir);
  const key = (p: string) => p.replace(/^"|"$/g, "").replace(/\//g, "\\").replace(/\\+$/, "").toLowerCase();
  return pathValue.split(";").some((p) => p && key(p) === key(dir));
}

/**
 * 사용자 환경 변수 Path(HKCU\Environment)에 $env:SUDAL_BIN_DIR 를 더하는 PowerShell. 관리자 권한이 필요 없다.
 * 결과는 JSON 줄로 낸다. 먼저 {"status":"present"|"added"|"tooLong"|"unsupported"|"unverified"} 를 내고,
 * added 면 이어서 {"notified":true|false|null} 을 낸다 — 알림이 늦어 시간 초과로 끊겨도 저장했다는 사실은 앞 줄로 남는다.
 *
 * - [Environment]::GetEnvironmentVariable 은 %USERPROFILE% 같은 변수를 풀어서 돌려주므로(다시 쓰면 원래 표기가 사라진다)
 *   레지스트리를 풀지 않고 읽어 그대로 이어 쓰고, 값의 종류(REG_SZ·REG_EXPAND_SZ)도 원래대로 둔다.
 * - 이미 있는지는 이 앱 프로세스의 PATH 가 아니라 레지스트리(사용자·시스템)로 본다 — 프로세스 PATH 는 임시로 잡혔거나 오래됐을 수 있다.
 *   %VAR% 는 값이 REG_EXPAND_SZ 일 때만 풀어 비교한다(REG_SZ 의 %VAR% 는 실제 환경에서도 풀리지 않는다).
 * - 더하면 cmd 가 무시하는 길이(8191자)를 넘을 것 같으면 바꾸지 않는다. 잘라서 저장하지 않는다.
 * - 저장한 뒤 다시 읽어 확인한다.
 * - 알림(WM_SETTINGCHANGE "Environment")을 받아야 탐색기에서 새로 띄우는 터미널 앱이 바뀐 Path 를 받는다.
 *   SetEnvironmentVariable 로 보내면 실패해도 알 수 없어서 SendMessageTimeout 의 반환값을 본다(응답 없는 창은 건너뛴다).
 *   Add-Type 이 막힌 환경(제한 언어 모드 등)이면 알 수 없음(null)으로 낸다.
 * 폴더 경로는 명령에 넣지 않고 환경 변수로 넘긴다(한글 사용자 이름·따옴표).
 */
export const ADD_TO_USER_PATH_PS = [
  "$ErrorActionPreference = 'Stop'",
  "function Out-Json($o) { [Console]::Out.WriteLine(($o | ConvertTo-Json -Compress)); [Console]::Out.Flush() }",
  "function Norm($p, $expand) { $q = $p.Trim().Trim('\"'); if ($expand) { $q = [Environment]::ExpandEnvironmentVariables($q) }; $q.Replace('/', '\\').TrimEnd('\\').ToLowerInvariant() }",
  "function Has($list, $dir, $expand) { $t = Norm $dir $true; @(([string]$list).Split(';') | Where-Object { $_.Trim() -and ((Norm $_ $expand) -eq $t) }).Count -gt 0 }",
  "$expandKind = [Microsoft.Win32.RegistryValueKind]::ExpandString",
  "$dir = $env:SUDAL_BIN_DIR",
  "$machineKey = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey('SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment')",
  // 시스템 Path 는 GetValue 가 REG_EXPAND_SZ 만 풀어서 준다 — 실제 환경에 들어가는 모양 그대로다
  "$machine = if ($machineKey) { [string]$machineKey.GetValue('Path', '') } else { '' }",
  "$key = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey('Environment')",
  "try {",
  "  $exists = $key.GetValueNames() -contains 'Path'",
  "  $cur = if ($exists) { [string]$key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames) } else { '' }",
  "  $kind = if ($exists) { $key.GetValueKind('Path') } else { $expandKind }",
  "  if ((Has $cur $dir ($kind -eq $expandKind)) -or (Has $machine $dir $false)) { Out-Json @{ status = 'present' }; return }",
  "  if ($kind -ne [Microsoft.Win32.RegistryValueKind]::String -and $kind -ne $expandKind) { Out-Json @{ status = 'unsupported' }; return }",
  "  $next = if ($cur.Trim()) { $cur.TrimEnd(';') + ';' + $dir } else { $dir }",
  "  $userLen = if ($kind -eq $expandKind) { [Environment]::ExpandEnvironmentVariables($next).Length } else { $next.Length }",
  "  if ($machine.Length + 1 + $userLen -gt 8191) { Out-Json @{ status = 'tooLong' }; return }",
  "  $key.SetValue('Path', $next, $kind)",
  "  if (-not (Has ([string]$key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)) $dir ($kind -eq $expandKind))) { Out-Json @{ status = 'unverified' }; return }",
  "  Out-Json @{ status = 'added' }",
  "} finally { $key.Close(); if ($machineKey) { $machineKey.Close() } }",
  "$notified = $null",
  "try {",
  "  Add-Type -Namespace SudalPath -Name Native -MemberDefinition '[DllImport(\"user32.dll\", CharSet = CharSet.Unicode)] public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);'",
  "  $r = [UIntPtr]::Zero",
  // HWND_BROADCAST, WM_SETTINGCHANGE, SMTO_ABORTIFHUNG, 창마다 최대 3초
  "  $notified = [SudalPath.Native]::SendMessageTimeout([IntPtr]0xffff, 0x1A, [UIntPtr]::Zero, 'Environment', 2, 3000, [ref]$r) -ne [IntPtr]::Zero",
  "} catch { }",
  "Out-Json @{ notified = $notified }",
].join("\n");

export type UserPathResult = { status: "present" | "added" | "tooLong" | "unsupported" | "unverified"; notified: boolean | null };

/**
 * 스크립트 출력의 JSON 줄들을 읽는다. status 줄이 없으면 null.
 * added 인데 notified 줄이 없으면(알림 중 시간 초과로 끊김) notified=false 로 본다.
 */
export function parseUserPathResult(stdout: string): UserPathResult | null {
  let status: UserPathResult["status"] | null = null;
  let notified: boolean | null | undefined;
  for (const line of stdout.split(/\r?\n/)) {
    let o: Record<string, unknown>;
    try {
      o = JSON.parse(line.trim()) as Record<string, unknown>;
    } catch {
      continue;
    }
    if (!o || typeof o !== "object") continue;
    const st = o.status;
    if (st === "present" || st === "added" || st === "tooLong" || st === "unsupported" || st === "unverified") status = st;
    if ("notified" in o) notified = typeof o.notified === "boolean" ? o.notified : null;
  }
  if (!status) return null;
  return { status, notified: status !== "added" ? false : notified === undefined ? false : notified };
}

/** PATH 값 끝에 dir 를 더한다. 이미 있으면 그대로, 비어 있으면 앞에 ; 를 붙이지 않는다. */
export function appendPathEntry(pathValue: string, dir: string): string {
  if (pathListHas(pathValue, dir, "win32")) return pathValue;
  const trimmed = pathValue.replace(/;+$/, "");
  return trimmed ? `${trimmed};${dir}` : dir;
}

/** powershell.exe -EncodedCommand 값(UTF-16LE base64). 따옴표·특수문자를 셸 규칙과 상관없이 넘긴다. */
export function encodePowerShell(script: string): string {
  return Buffer.from(script, "utf16le").toString("base64");
}
