import { test } from "node:test";
import assert from "node:assert/strict";
import { ADD_TO_USER_PATH_PS, appendPathEntry, cmdPathLiteral, encodePowerShell, parseUserPathResult, pathListHas, windowsCliBinDir, windowsCmdShim, windowsShShim } from "./cli-shim";

const ENV = {
  LOCALAPPDATA: "C:\\Users\\김수달\\AppData\\Local",
  APPDATA: "C:\\Users\\김수달\\AppData\\Roaming",
  USERPROFILE: "C:\\Users\\김수달",
};
const TARGET = {
  exe: "C:\\Users\\김수달\\AppData\\Local\\Programs\\sudal\\Sudal.exe",
  cjs: "C:\\Users\\김수달\\AppData\\Local\\Programs\\sudal\\resources\\cli\\sudal.cjs",
  userData: "C:\\Users\\김수달\\AppData\\Roaming\\Sudal",
};

test("windowsCliBinDir: %LOCALAPPDATA%\\Sudal\\bin, 없으면 홈 아래 AppData\\Local", () => {
  assert.equal(windowsCliBinDir(ENV, "C:\\Users\\x"), "C:\\Users\\김수달\\AppData\\Local\\Sudal\\bin");
  assert.equal(windowsCliBinDir({}, "C:\\Users\\x"), "C:\\Users\\x\\AppData\\Local\\Sudal\\bin");
});

test("cmdPathLiteral: 알려진 앞부분은 변수로(한글이 .cmd 에 안 남게), % 는 %%", () => {
  assert.equal(cmdPathLiteral(TARGET.exe, ENV), "%LOCALAPPDATA%\\Programs\\sudal\\Sudal.exe");
  assert.equal(cmdPathLiteral(TARGET.userData, ENV), "%APPDATA%\\Sudal");
  assert.equal(cmdPathLiteral("c:\\users\\김수달\\x", ENV), "%USERPROFILE%\\x");
  assert.equal(cmdPathLiteral("D:\\100%\\Sudal.exe", ENV), "D:\\100%%\\Sudal.exe");
  // 앞부분이 이름 일부만 겹치면 바꾸지 않는다
  assert.equal(cmdPathLiteral("C:\\Users\\김수달2\\x", ENV), "C:\\Users\\김수달2\\x");
});

test("windowsCmdShim: setlocal·SUDAL_USERDATA 기본값·ELECTRON_RUN_AS_NODE·%* 를 CRLF 로, 내용은 ASCII", () => {
  const s = windowsCmdShim(TARGET, ENV);
  assert.equal(
    s,
    [
      "@echo off",
      "rem Sudal CLI (generated by the Sudal app; reinstall from Settings to update)",
      "setlocal",
      'if not defined SUDAL_USERDATA set "SUDAL_USERDATA=%APPDATA%\\Sudal"',
      "set ELECTRON_RUN_AS_NODE=1",
      '"%LOCALAPPDATA%\\Programs\\sudal\\Sudal.exe" "%LOCALAPPDATA%\\Programs\\sudal\\resources\\cli\\sudal.cjs" %*',
      "",
    ].join("\r\n"),
  );
  assert.ok(/^[\x00-\x7f]*$/.test(s));
});

test("windowsShShim: 실행 경로는 / 로, SUDAL_USERDATA 기본값은 원래 표기 그대로", () => {
  const s = windowsShShim({ exe: "C:\\Program Files\\Sudal\\Sudal.exe", cjs: "C:\\Program Files\\Sudal\\resources\\cli\\sudal.cjs", userData: "C:\\Users\\a$b\\Sudal" });
  assert.ok(s.startsWith("#!/bin/sh\n"));
  assert.ok(s.includes(': "${SUDAL_USERDATA:=C:\\\\Users\\\\a\\$b\\\\Sudal}"'), s);
  assert.ok(s.includes("ELECTRON_RUN_AS_NODE=1 exec 'C:/Program Files/Sudal/Sudal.exe' 'C:/Program Files/Sudal/resources/cli/sudal.cjs' \"$@\""), s);
});

test("pathListHas: macOS 는 : 와 정확한 비교, win32 는 ; 와 대소문자·끝 구분자·따옴표 무시", () => {
  assert.equal(pathListHas("/usr/bin:/Users/a/.local/bin/", "/Users/a/.local/bin", "darwin"), true);
  assert.equal(pathListHas("/usr/bin:/Users/A/.local/bin", "/Users/a/.local/bin", "darwin"), false);
  const dir = "C:\\Users\\a\\AppData\\Local\\Sudal\\bin";
  assert.equal(pathListHas("C:\\Windows;c:\\users\\a\\appdata\\local\\sudal\\bin\\", dir, "win32"), true);
  assert.equal(pathListHas('C:\\Windows;"C:\\Users\\a\\AppData\\Local\\Sudal\\bin"', dir, "win32"), true);
  assert.equal(pathListHas("C:\\Windows;C:\\Users\\a\\AppData\\Local\\Sudal", dir, "win32"), false);
});

test("사용자 Path 에 더하는 PowerShell 은 폴더를 명령에 넣지 않고 인코딩해서 넘긴다", () => {
  // 한글 사용자 이름·따옴표가 섞인 경로도 명령 줄 규칙과 상관없게 환경 변수로 받는다
  assert.match(ADD_TO_USER_PATH_PS, /\$env:SUDAL_BIN_DIR/);
  // 레지스트리 값의 %USERPROFILE% 같은 표기를 풀지 않고 이어 쓴다
  assert.match(ADD_TO_USER_PATH_PS, /DoNotExpandEnvironmentNames/);
  // 원래 값의 종류(REG_SZ·REG_EXPAND_SZ)를 그대로 쓴다
  assert.match(ADD_TO_USER_PATH_PS, /GetValueKind\('Path'\)/);
  assert.match(ADD_TO_USER_PATH_PS, /SetValue\('Path', \$next, \$kind\)/);
  // 알림은 실패를 알 수 있는 SendMessageTimeout 으로, 저장 결과는 그 전에 낸다
  assert.match(ADD_TO_USER_PATH_PS, /SendMessageTimeout/);
  assert.ok(ADD_TO_USER_PATH_PS.indexOf("status = 'added'") < ADD_TO_USER_PATH_PS.indexOf("SendMessageTimeout("));
  const encoded = encodePowerShell("Write-Output '수달'");
  assert.equal(Buffer.from(encoded, "base64").toString("utf16le"), "Write-Output '수달'");
});

test("Path 스크립트 결과는 마지막 JSON 줄을 읽는다", () => {
  assert.deepEqual(parseUserPathResult('경고 한 줄\r\n{"notified":true,"status":"added"}\r\n'), { status: "added", notified: true });
  assert.deepEqual(parseUserPathResult('{"status":"present","notified":false}'), { status: "present", notified: false });
  // 저장 뒤 알림 결과는 다음 줄로 온다
  assert.deepEqual(parseUserPathResult('{"status":"added"}\n{"notified":false}'), { status: "added", notified: false });
  assert.deepEqual(parseUserPathResult('{"status":"added"}\n{"notified":null}'), { status: "added", notified: null });
  // 알림 중 시간 초과로 끊겼다 — 저장은 됐고 알림은 실패로 본다
  assert.deepEqual(parseUserPathResult('{"status":"added"}\n'), { status: "added", notified: false });
  assert.equal(parseUserPathResult('{"status":"weird"}'), null);
  assert.equal(parseUserPathResult(""), null);
});

test("PATH 끝에 폴더를 더할 때 빈 값·중복·끝 구분자를 맞춘다", () => {
  const dir = "C:\\Users\\김수달\\AppData\\Local\\Sudal\\bin";
  assert.equal(appendPathEntry("", dir), dir);
  assert.equal(appendPathEntry("C:\\a;", dir), `C:\\a;${dir}`);
  assert.equal(appendPathEntry(`C:\\a;${dir.toLowerCase()}\\`, dir), `C:\\a;${dir.toLowerCase()}\\`);
  // / 로 적힌 같은 폴더도 이미 있는 것으로 본다
  assert.equal(appendPathEntry(dir.replace(/\\/g, "/"), dir), dir.replace(/\\/g, "/"));
});
