import { test } from "node:test";
import assert from "node:assert/strict";
import { ADD_TO_USER_PATH_PS, cmdPathLiteral, encodePowerShell, pathListHas, windowsCliBinDir, windowsCmdShim, windowsShShim } from "./cli-shim";

const ENV = {
  LOCALAPPDATA: "C:\\Users\\김수달\\AppData\\Local",
  APPDATA: "C:\\Users\\김수달\\AppData\\Roaming",
  USERPROFILE: "C:\\Users\\김수달",
};
const TARGET = {
  exe: "C:\\Users\\김수달\\AppData\\Local\\Programs\\sudal\\Sudal.exe",
  cjs: "C:\\Users\\김수달\\AppData\\Local\\Programs\\sudal\\resources\\cli\\sudal.cjs",
  userData: "C:\\Users\\김수달\\AppData\\Roaming\\Sudal",
};

test("windowsCliBinDir: %LOCALAPPDATA%\\Sudal\\bin, 없으면 홈 아래 AppData\\Local", () => {
  assert.equal(windowsCliBinDir(ENV, "C:\\Users\\x"), "C:\\Users\\김수달\\AppData\\Local\\Sudal\\bin");
  assert.equal(windowsCliBinDir({}, "C:\\Users\\x"), "C:\\Users\\x\\AppData\\Local\\Sudal\\bin");
});

test("cmdPathLiteral: 알려진 앞부분은 변수로(한글이 .cmd 에 안 남게), % 는 %%", () => {
  assert.equal(cmdPathLiteral(TARGET.exe, ENV), "%LOCALAPPDATA%\\Programs\\sudal\\Sudal.exe");
  assert.equal(cmdPathLiteral(TARGET.userData, ENV), "%APPDATA%\\Sudal");
  assert.equal(cmdPathLiteral("c:\\users\\김수달\\x", ENV), "%USERPROFILE%\\x");
  assert.equal(cmdPathLiteral("D:\\100%\\Sudal.exe", ENV), "D:\\100%%\\Sudal.exe");
  // 앞부분이 이름 일부만 겹치면 바꾸지 않는다
  assert.equal(cmdPathLiteral("C:\\Users\\김수달2\\x", ENV), "C:\\Users\\김수달2\\x");
});

test("windowsCmdShim: setlocal·SUDAL_USERDATA 기본값·ELECTRON_RUN_AS_NODE·%* 를 CRLF 로, 내용은 ASCII", () => {
  const s = windowsCmdShim(TARGET, ENV);
  assert.equal(
    s,
    [
      "@echo off",
      "rem Sudal CLI (generated by the Sudal app; reinstall from Settings to update)",
      "setlocal",
      'if not defined SUDAL_USERDATA set "SUDAL_USERDATA=%APPDATA%\\Sudal"',
      "set ELECTRON_RUN_AS_NODE=1",
      '"%LOCALAPPDATA%\\Programs\\sudal\\Sudal.exe" "%LOCALAPPDATA%\\Programs\\sudal\\resources\\cli\\sudal.cjs" %*',
      "",
    ].join("\r\n"),
  );
  assert.ok(/^[\x00-\x7f]*$/.test(s));
});

test("windowsShShim: 실행 경로는 / 로, SUDAL_USERDATA 기본값은 원래 표기 그대로", () => {
  const s = windowsShShim({ exe: "C:\\Program Files\\Sudal\\Sudal.exe", cjs: "C:\\Program Files\\Sudal\\resources\\cli\\sudal.cjs", userData: "C:\\Users\\a$b\\Sudal" });
  assert.ok(s.startsWith("#!/bin/sh\n"));
  assert.ok(s.includes(': "${SUDAL_USERDATA:=C:\\\\Users\\\\a\\$b\\\\Sudal}"'), s);
  assert.ok(s.includes("ELECTRON_RUN_AS_NODE=1 exec 'C:/Program Files/Sudal/Sudal.exe' 'C:/Program Files/Sudal/resources/cli/sudal.cjs' \"$@\""), s);
});

test("pathListHas: macOS 는 : 와 정확한 비교, win32 는 ; 와 대소문자·끝 구분자·따옴표 무시", () => {
  assert.equal(pathListHas("/usr/bin:/Users/a/.local/bin/", "/Users/a/.local/bin", "darwin"), true);
  assert.equal(pathListHas("/usr/bin:/Users/A/.local/bin", "/Users/a/.local/bin", "darwin"), false);
  const dir = "C:\\Users\\a\\AppData\\Local\\Sudal\\bin";
  assert.equal(pathListHas("C:\\Windows;c:\\users\\a\\appdata\\local\\sudal\\bin\\", dir, "win32"), true);
  assert.equal(pathListHas('C:\\Windows;"C:\\Users\\a\\AppData\\Local\\Sudal\\bin"', dir, "win32"), true);
  assert.equal(pathListHas("C:\\Windows;C:\\Users\\a\\AppData\\Local\\Sudal", dir, "win32"), false);
});

test("사용자 Path 에 더하는 PowerShell 은 폴더를 명령에 넣지 않고 인코딩해서 넘긴다", () => {
  // 한글 사용자 이름·따옴표가 섞인 경로도 명령 줄 규칙과 상관없게 환경 변수로 받는다
  assert.match(ADD_TO_USER_PATH_PS, /\$env:SUDAL_BIN_DIR/);
  // 레지스트리 값의 %USERPROFILE% 같은 표기를 풀지 않고 이어 쓴다
  assert.match(ADD_TO_USER_PATH_PS, /DoNotExpandEnvironmentNames/);
  assert.match(ADD_TO_USER_PATH_PS, /ExpandString/);
  const encoded = encodePowerShell("Write-Output '수달'");
  assert.equal(Buffer.from(encoded, "base64").toString("utf16le"), "Write-Output '수달'");
});
