// Windows 용 `sudal` CLI shim 만들기. macOS 의 ~/.local/bin/sudal(#!/bin/sh)에 해당한다.
// 한 폴더에 sudal.cmd(cmd·PowerShell)와 확장자 없는 sudal(Git Bash — Claude Code 의 Bash 도구가 쓴다)을 함께 둔다.
// npm 이 전역 명령을 까는 방식과 같아서, 그 폴더가 PATH 에 있으면 어느 셸에서든 `sudal` 로 부를 수 있다.

import path from "node:path";

const w = path.win32;

/** %LOCALAPPDATA%\Sudal\bin — 사용자가 설치하는 shim 자리. */
export function windowsCliBinDir(env: NodeJS.ProcessEnv, home: string): string {
  return w.join(env.LOCALAPPDATA || w.join(home, "AppData", "Local"), "Sudal", "bin");
}

/**
 * .cmd 에 넣을 경로 표기. cmd.exe 는 배치 파일을 시스템 코드 페이지(한국어 Windows 는 949)로 읽어서
 * UTF-8 로 쓴 한글 경로(사용자 이름 등)가 깨진다. 그래서 알려진 앞부분을 %LOCALAPPDATA% 같은 변수로 바꿔 ASCII 로 남기고,
 * 나머지의 % 는 %% 로 막는다.
 */
export function cmdPathLiteral(p: string, env: NodeJS.ProcessEnv): string {
  for (const name of ["LOCALAPPDATA", "APPDATA", "USERPROFILE"]) {
    const base = env[name]?.replace(/[\\/]+$/, "");
    if (base && p.toLowerCase().startsWith(`${base.toLowerCase()}\\`)) return `%${name}%${p.slice(base.length).replace(/%/g, "%%")}`;
  }
  return p.replace(/%/g, "%%");
}

export interface ShimTarget {
  /** Sudal.exe(process.execPath) */
  exe: string;
  /** 동봉 resources\cli\sudal.cjs */
  cjs: string;
  /** 이 앱의 userData — SUDAL_USERDATA 기본값 */
  userData: string;
}

/** sudal.cmd. setlocal 로 감싸 ELECTRON_RUN_AS_NODE 가 부른 cmd 세션에 남지 않게 한다. */
export function windowsCmdShim(t: ShimTarget, env: NodeJS.ProcessEnv): string {
  return [
    "@echo off",
    "rem Sudal CLI (generated by the Sudal app; reinstall from Settings to update)",
    "setlocal",
    `if not defined SUDAL_USERDATA set "SUDAL_USERDATA=${cmdPathLiteral(t.userData, env)}"`,
    "set ELECTRON_RUN_AS_NODE=1",
    `"${cmdPathLiteral(t.exe, env)}" "${cmdPathLiteral(t.cjs, env)}" %*`,
    "",
  ].join("\r\n");
}

const shQuote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;

/** Git Bash(MSYS)용 sh 스크립트. 실행 경로는 / 로 바꾼다(MSYS 와 node 모두 C:/... 를 받는다). */
export function windowsShShim(t: ShimTarget): string {
  const fwd = (p: string) => p.replace(/\\/g, "/");
  return [
    "#!/bin/sh",
    "# Sudal CLI (generated by the Sudal app; reinstall from Settings to update)",
    // 기본값은 큰따옴표 안이라 \ " $ ` 만 막으면 원래 표기(C:\...)가 그대로 들어간다 — 앱이 넘기는 값과 같아야 제어 파이프 이름이 맞는다
    `: "\${SUDAL_USERDATA:=${t.userData.replace(/[\\"$`]/g, "\\$&")}}"`,
    "export SUDAL_USERDATA",
    `ELECTRON_RUN_AS_NODE=1 exec ${shQuote(fwd(t.exe))} ${shQuote(fwd(t.cjs))} "$@"`,
    "",
  ].join("\n");
}

/** PATH 값에 dir 이 있는가. win32 는 ; 로 나누고 대소문자·끝 구분자를 무시한다. */
export function pathListHas(pathValue: string, dir: string, platform: NodeJS.Platform): boolean {
  if (platform !== "win32") return pathValue.split(":").some((p) => p.replace(/\/+$/, "") === dir);
  const key = (p: string) => p.replace(/^"|"$/g, "").replace(/[\\/]+$/, "").toLowerCase();
  return pathValue.split(";").some((p) => p && key(p) === key(dir));
}
